
development:
  adapter: postgresql
  encoding: unicode
  database: sanguosha_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: sanguosha_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: sanguosha_production
  pool: 5

